version: '2'
services:
  proxy_pool:
    volumes:
     - ..:/root/docker-file/IPProxy
    ports:
     - "5000:5000"
    links:
     - proxy_redis
    image: "proxy_pool"
  proxy_redis:
    ports:
     - "6379:6379"
    image: "redis"